#!/usr/bin/php
<?php

$script = 'daemon';
require_once('initialize.php');

$player = new csPlayer($mplayerfifo, $cachesize);
$check = 0;

while (true) 
{
  // what's in the message queue?
  while ($msg = csMsgQueue::getNext())
  {
    echo "Received message: $msg\n";
    
    $msg = trim($msg);
    
    switch ($msg)
    {
      case 'pause':
        echo "Pausing player\n";
        $player->pause();
        break;
      case 'stop':
        exit;
        break;
    }
  }
  
  $check--;
  
  if ($check <= 0 && !$player->isPaused())
  {
    $timeLeft = $player->getTimeLeft();

    // should we be loading the next song?
    if ($timeLeft <= $bufferTime)
    {
      // update the queue
      $queue = csQueue::get();
      $entries = $queue->getEntries();

      foreach ($entries as $key => $entry)
      {
        // find the first unprocessed entry in the queue
        if (!$entry->wasProcessed())
        {
          $player->loadSong($entry);
          echo "Processing entry!\n";
          $queue->processEntry($key);
          $queue->setPos($key);
          break;
        }
      }
    }
  
    // there are more than 30 seconds left in the current song
    // unless we receive input to take action, we'll check again in 20
    if ($timeLeft > 30 )
    {
      $check = 20;
    }
    // there are more than 10 seconds left in the current song
    // we'll check back in 5
    elseif ($timeLeft > 10)
    {
      $check = 5;
    }
    // the song will be ending soon, check each frame
    else
    {
      $check = 0;
    }
  }
  
  echo "timeleft: $timeLeft\n";
  sleep(1);
}