#!/usr/bin/php
<?php
// Config file is required
require('settings.inc.php');
require('functions.php');



$songcount = 0;

// Shared Memory Setup
$shmem = shm_attach(SHM_KEY);

// Get Current PID and put in shared mem (For the helper program)
$mainpid = getmypid();
shm_put_var($shmem, SHM_PID_KEY, $mainpid);
// Set the queue to null in case anything is still around from last run.
$queue = null;
shm_put_var($shmem, SHM_QUEUE_KEY, $queue);
$timeLeft = 0;
shm_put_var($shmem, SHM_TIMELEFT_KEY, $timeLeft);
$isPaused = false;
shm_put_var($shmem, SHM_ISPAUSED_KEY, $isPaused);
// Launch helper program.
exec('./helper > /tmp/helperout 2>&1 &');


$artists_arr = getArtists();

while (1) 
{
  system('clear');
  echo "##############################\n";
  echo "#     clisonic main menu     #\n";
  echo "##############################\n";
  echo "\n";
  echo "1: Add Song/Album\n";
  echo "2: View Queue\n";
  echo "3: Clear Queue\n";
  echo "u: Pause/Unpause\n";
  echo "n: Next\n";
  echo "p: Prev\n";
  echo "q: Quit\n";

  echo "Enter your choice: ";

  $choice = trim(fgets($stdio));


  switch ($choice)
  {
    case 1:
      addToQueue();
      break;
    case 2:
      viewQueue();
      break;
    case 3:
      clearQueue();
      break;
    case 'u':
      pauseSong();
      break;
    case 'n':
      nextSong();
      break;
    case 'p':
      prevSong();
      break;
    case 'q':
      shm_remove($shmem);
      exit(0);
      break;
    default:
      echo "I did not understand your command. Press enter to try again.";
      fgets($stdio);
  }

}

?>
