#!/usr/bin/php
<?php

require_once('initialize.php');

csPlayer::init($mplayerfifo, $cachesize);

$mainpid = csMemory::get(SHM_PID_KEY);
$timeLeft = 0;

$kg = true;

while ($kg) 
{
  // should we be loading the next song?
  if ($timeLeft <= $bufferTime)
  {
    // update the queue
    $queue = csQueue::get();
    
    foreach ($queue as $key => &$entry)
    {
      // find the first unprocessed entry in the queue
      if (!$entry->wasProcessed())
      {
        csPlayer::loadSong($entry);
        csPlayer::setTimeLeft($entry->getDuration());
        csQueue::setPos($key);
        echo "Processing entry!\n";
        $entry->setProcessed(true);
        csQueue::set($queue);
        break;
      }
    }
  }

  sleep(1);
  $timeLeft = csPlayer::getTimeLeft();  
  $isPaused = csPlayer::isPaused();
  
  if (!$isPaused)
    $timeLeft--;
  
  csPlayer::setTimeLeft($timeLeft);
  echo "timeleft: $timeLeft\n";
  
  system("ps -p $mainpid > /dev/null", $retval);
  
  $kg = ($retval == 0);
}
